### ISSUE TITLE
Hi. I'm working on a game for this display with MSP430F5529 and would like to know if you can give some tips?

### ISSUE THREAD

**Issue by emmenezes** [trajano7/Tetris_C_MSP430_LCDNOKIA5110#1]
Hi, I'm an UnB student, major Computer Engineering, and I have a project with this display, but I'm lost right now and would like to know if you could help me. My project is about Google's Dino Game.

**Comment by trajano7** [comment]
Oi, também sou aluno de engenharia de computação na UnB, só percebi agora que não tinha essa informação no perfil. Então, você está tendo algum problemas mais especificamente? Digo, problema em usar o LCD ou no jogo.

**Comment by emmenezes** [comment]
Oi kk eu imaginei que vc poderia ser da UnB, mas decidi nãoa rriscar escrver em pt-br, porque vai que eu estivesse errada
O problema era mais o LCD, eu estava buscando bibliotecas para o display no Google, mas não tinha achada nada muito claro, e ontem, procurando aqui no Git, eu achei a sua aplicação bem mais similar à minha e queria entender como funciona.

**Comment by trajano7** [comment]
Quando eu utilizei não achei biblioteca pronta, no máximo para arduino, então eu utilizei como referência a documentação do LCD que você consegue achar na internet e de outros códigos que utilizam ele. Que eu me lembre ele tem 2 modos de funcionamento, em um você percorre as 84 colunas de uma em uma e as linhas de byte em byte, então cada dado mandado para ser mostrado tem 8 bits, cada bit um pixel daquela coluna, e ai o outro modo acho que funciona ao contrario disso. Além disso tem como por ele no modo comando por um dos pinos, que ai você consegue mandar comandos ao invés de dados, por exemplo tem um comando de colocar o cursor em uma posição especifica da tela.

**Comment by emmenezes** [comment]
Hmmm saquei, eu vou conferir isso também. Hoje eu tirei o dia para tentar rodar o seu código, assim eu garanto que pelo menos entendi a conexão e o display está funcionando bem. Mas, nesse processo, eu simplesmente não consigo rodar. Colocando o resistor no backlight também não foi (?), eu só consegui ligar conectando direto no terra. Quando eu executo o programa no modo debug, ele vai passando pelas operações no entanto não vejo nenhum sinal visual. Vc teria algum palpite de onde estou errando?

**Comment by trajano7** [comment]
Faz um tempo que não monto o circuito, então não lembro muito do processo, mas acredito que era necessário somente ligar e rodar. O modelo do seu MSP e do LCD é o mesmo? Qualquer coisa posso testar aqui no meu, vê se ainda funciona.

**Comment by emmenezes** [comment]
Hoje eu testei com um ESP32 um código pronto pra escrever só uma frase e percebi que só funcionava 1 de 10 vezes :( acho que ela queimou ou veio com defeito, então vamos arrumar outro projeto para sexta. Mas muito obrigada pelo apoio! Eu achei muito interessante essa aplicação e muito divertido o resultado final.
